GET  http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{ "content": "Pelos es un gato tonto"
}

####
POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
  "content": "Sent via VSCode!!!",
  "important": true
}

// create user
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "ternerita",
  "name":"pati",
  "password": "abc"
}

// login requests
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "ternerita",
  "password":"abc"
}